### ISSUE TITLE
Hey Cousin! 

### ISSUE THREAD

**Issue by McKlayne** [drautb/bookshelf-to-kindle#1]
I was searching for a way to read bookshelf books on my kindle scribe and came across your repo. Made my day!! Based on your message in 2018, I am guessing you haven’t found a work-around. 

Anyways, hope you are doing well.

**Comment by drautb** [comment]
Hey! Nope, I abandoned this after that 2018 note, sorry! Definitely didn't expect to run into you on GitHub of all places! 😄 Hope you're doing well too.
